festi_vite_main:
    path:     /main
    defaults: { _controller: FestiViteBundle:Default:main }

festi_vite_creersoiree:
    path:     /creersoiree
    defaults: { _controller: FestiViteBundle:Default:creersoiree }

festi_vite_moncompte:
    path:     /moncompte
    defaults: { _controller: FestiViteBundle:Default:moncompte }

festi_vite_accueil:
    path:     /accueil
    defaults: { _controller: FestiViteBundle:Default:accueil }

festi_vite_recherche:
    path:     /recherche
    defaults: { _controller: FestiViteBundle:Default:recherche }

festi_vite_login:
    path:     /login
    defaults: { _controller: FestiViteBundle:Security:login}

festi_test:
    path:     /test
    defaults: { _controller: FestiViteBundle:Default:test }

festi_test_soiree:
    path:     /test/createsoiree
    defaults: { _controller: FestiViteBundle:Default:createsoiree }

festi_test_connection:
    path:     /test/connection
    defaults: { _controller: FestiViteBundle:Default:connection }
