festi_vite_main:
    path:     /main
    defaults: { _controller: FestiViteBundle:Default:main }

festi_vite_creersoiree:
    path:     /creersoireeclassique
    defaults: { _controller: FestiViteBundle:Default:creersoireeclassique }

festi_vite_creersoiree:
    path:     /creersoireeaventure
    defaults: { _controller: FestiViteBundle:Default:creersoireeaventure }

festi_vite_moncompte:
    path:     /moncompte
    defaults: { _controller: FestiViteBundle:Default:moncompte }

festi_vite_accueil:
    path:     /accueil
    defaults: { _controller: FestiViteBundle:Security:login }

festi_vite_recherche:
    path:     /rechercheprestataire
    defaults: { _controller: FestiViteBundle:Default:recherche }

festi_vite_prestataire:
    path:    /prestataire
    defaults: { _controller: FestiViteBundle:Default:prestataire}

festi_test:
    path:     /test
    defaults: { _controller: FestiViteBundle:Default:test }

festi_test_soiree:
    path:     /test/createsoiree
    defaults: { _controller: FestiViteBundle:Default:createsoiree }

festi_test_connection:
    path:     /test/connection
    defaults: { _controller: FestiViteBundle:Default:connection }

festi_redirect:
  path:       /redirect
  defaults: { _controller: FestiViteBundle:Default:redirect}

festi_vite_ajoutprestataire:
    path:     /ajoutprestataire
    defaults: { _controller: FestiViteBundle:Default:ajoutprestataire }
