festi_vite:
    resource: "@FestiViteBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path: /accueil
    defaults:
        _controller: FestiViteBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
