security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        FestiViteBundle\Entity\Utilisateur: sha512
        FestiViteBundle\Entity\UtilisateurProfessionnel: sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_PREST]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_PREST, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        chain_provider:
          chain:
            providers: [prest, main]
        main:
          entity:
            class:  FestiViteBundle\Entity\Utilisateur
            property: adresseMail

        prest:
          entity:
            class:  FestiViteBundle\Entity\UtilisateurProfessionnel
            property: adresseMail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:      ^/
            anonymous:    true
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: /redirect
            logout:
                path:       logout
                target:     /accueil



    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
