security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        FestiViteBundle\Entity\Utilisateur: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
          entity:
            class:  FestiViteBundle\Entity\Utilisateur
            property: adresseMail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:      ^/
            anonymous:    true
            provider:     main
            form_login:
                login_path: login
                check_path: login_check
                default_target_path: festi_vite_main
            logout:
                path:       logout
                target:     /accueil

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
